from requests_html import HTML

with open(r"./simple.html", "r") as html_file:
    source = html_file.read()
    html = HTML(html=source)

    # this renders the page and adds the dynamic elements that are added to the html  with javascript.
    html.render()

match = html.find("#footer", first=True)

# if you don't render the html first you won't get the paragraph generated by javascript
print(match.html)
